import { FORM_TYPE } from "@/constants/shared/form";
import { GENDER_OPTIONS, CATEGORY_OPTIONS } from "./common";
import type { FormFieldConfig } from "@/types/formTypes";

export const STUDENT_ADMISSION_FORM_INITIAL_DATA = {
  admission_head_id: "" as string | number,
  applicant_name: "",
  father_name: "",
  mother_name: "",
  father_qualification: "",
  father_occupation: "",
  father_mobile: "",
  dob: "",
  gender: "",
  category: "",
  caste: "",
  mobile: "",
  aadhar_no: "",
  marital_status: "",
  religion: "",
  is_differently_abled: false,
  university_roll_no: "",
  reg_no: "",
  abc_no: "",
  apaar_id: "",
  roll_no: "",
  place: "",
  signature_url: "",

  addresses: [
    {
      address_type: "permanent",
      village_mohalla: "",
      post_office: "",
      police_station: "",
      district: "",
      state: "",
      pincode: "",
    },
    {
      address_type: "correspondence",
      village_mohalla: "",
      post_office: "",
      police_station: "",
      district: "",
      state: "",
      pincode: "",
    },
  ],

  last_academic: {
    institute_name: "",
    class: "",
    session: "",
    section: "",
    roll_number: "",
  },

  previous_exams: [] as any[],
  selected_subjects: [] as {
    subject_id: number;
    subject_category_id: number;
  }[],
  documents: [
    { doc_type: "photo", doc_path: "" },
    { doc_type: "migration", doc_path: "" },
    { doc_type: "clc", doc_path: "" },
  ],
};

export const STUDENT_ADMISSION_FORM_FIELDS: FormFieldConfig[] = [
  {
    section: "Basic Details",
    name: "applicant_name",
    label: "Applicant Name",
    type: FORM_TYPE.TEXT,
    placeholder: "e.g. Full name as in 10th certificate",
    tooltip: "Applicant's full name. Must match the name on academic and identity documents.",
    required: true,
    maxLength: 100,
    permission: "field_admission_applicant_name",
  },
  {
    name: "roll_no",
    label: "Roll No",
    type: FORM_TYPE.TEXT,
    placeholder: "e.g. 12345",
    tooltip: "Roll number if already assigned by the institution.",
    maxLength: 30,
    permission: "field_admission_roll_no",
  },
  {
    name: "father_name",
    label: "Father Name",
    type: FORM_TYPE.TEXT,
    placeholder: "e.g. Father's full name",
    tooltip: "Full name of father or legal guardian as in official records.",
    required: true,
    maxLength: 100,
    permission: "field_admission_father_name",
  },
  {
    name: "father_qualification",
    label: "Father Qualification",
    type: FORM_TYPE.TEXT,
    placeholder: "e.g. Graduate, Post Graduate",
    tooltip: "Highest educational qualification of father/guardian.",
    required: true,
    maxLength: 100,
    permission: "field_admission_father_qual",
  },
  {
    name: "father_occupation",
    label: "Father Occupation",
    type: FORM_TYPE.TEXT,
    placeholder: "e.g. Business, Service",
    tooltip: "Occupation or profession of father/guardian.",
    required: true,
    maxLength: 100,
    permission: "field_admission_father_occ",
  },
  {
    name: "mother_name",
    label: "Mother Name",
    type: FORM_TYPE.TEXT,
    placeholder: "e.g. Mother's full name",
    tooltip: "Full name of mother as in official records.",
    required: true,
    maxLength: 100,
    permission: "field_admission_mother_name",
  },
  {
    name: "dob",
    label: "Date of Birth",
    type: FORM_TYPE.DATE,
    placeholder: "e.g. DD/MM/YYYY",
    tooltip: "Date of birth as per 10th certificate or birth certificate.",
    required: true,
    permission: "field_admission_dob",
  },
  {
    name: "gender",
    label: "Gender",
    type: FORM_TYPE.DROPDOWN,
    placeholder: "e.g. Select gender",
    tooltip: "Gender as per official records.",
    required: true,
    options: GENDER_OPTIONS,
    permission: "field_admission_gender",
  },
  {
    name: "category",
    label: "Category",
    placeholder: "e.g. Select Category",
    tooltip: "Reservation category (General, SC, ST, BC, EWS) as per certificate.",
    type: FORM_TYPE.DROPDOWN,
    options: CATEGORY_OPTIONS,
    permission: "field_admission_category",
  },
  {
    name: "caste",
    label: "Caste",
    type: FORM_TYPE.TEXT,
    placeholder: "e.g. As per certificate",
    tooltip: "Caste as mentioned in the category/caste certificate, if applicable.",
    required: true,
    maxLength: 50,
    permission: "field_admission_caste",
  },
  {
    name: "nationality",
    label: "Nationality",
    type: FORM_TYPE.TEXT,
    placeholder: "e.g. Indian",
    tooltip: "Nationality of the applicant.",
    maxLength: 50,
    permission: "field_admission_nationality",
  },
  {
    name: "religion",
    label: "Religion",
    type: FORM_TYPE.TEXT,
    placeholder: "e.g. As per records",
    tooltip: "Religion of the applicant as in official records.",
    required: true,
    maxLength: 50,
    permission: "field_admission_religion",
  },
  {
    name: "marital_status",
    label: "Marital status",
    type: FORM_TYPE.DROPDOWN,
    required: true,
    options: [
      { key: "Married", value: "Married", text: "Married" },
      { key: "Unmarried", value: "Unmarried", text: "Unmarried" },
    ],
    permission: "field_admission_marital_status",
  },
  {
    name: "blood_group",
    label: "Blood Group",
    placeholder: "Select Blood Group",
    type: FORM_TYPE.DROPDOWN,
    options: [
      { key: "a+", value: "a+", text: "A+" },
      { key: "a-", value: "a-", text: "A-" },
      { key: "b+", value: "b+", text: "B+" },
      { key: "b-", value: "b-", text: "B-" },
      { key: "ab+", value: "ab+", text: "AB+" },
      { key: "ab-", value: "ab-", text: "AB-" },
      { key: "o+", value: "o+", text: "O+" },
      { key: "o-", value: "o-", text: "O-" },
    ],
    permission: "field_admission_blood_group",
  },
  {
    name: "is_differently_abled",
    label: "Is Differently Abled?",
    type: FORM_TYPE.DROPDOWN,
    options: [
      { key: "yes", value: true, text: "Yes" },
      { key: "no", value: false, text: "No" },
    ],
    permission: "field_admission_differently_abled",
  },

  // ===== CONTACT =====
  {
    name: "mobile",
    label: "Mobile Number",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_mobile",
  },
  {
    name: "father_mobile",
    label: "Father Mobile",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_father_mobile",
  },

  // ===== IDENTITY =====
  {
    section: "Identity",
    name: "aadhar_no",
    label: "Aadhaar Number",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_aadhar_no",
  },
  {
    name: "abc_no",
    label: "ABC ID",
    type: FORM_TYPE.TEXT,
    placeholder: "e.g. 12-digit ABC ID",
    tooltip: "Academic Bank of Credits ID.",
    required: true,
    maxLength: 50,
    permission: "field_admission_abc_no",
  },
  {
    name: "apaar_id",
    label: "APAAR ID",
    type: FORM_TYPE.TEXT,
    placeholder: "e.g. APAAR ID",
    tooltip: "Automated Permanent Academic Account Registry ID.",
    maxLength: 50,
    permission: "field_admission_apaar_id",
  },

  // ===== ADDRESS (PERMANENT) =====
  {
    section: "Permanent Address",
    name: "addresses.0.village_mohalla",
    label: "Village / Mohalla",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_perm_village",
  },
  {
    name: "addresses.0.post_office",
    label: "Post Office",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_perm_post",
  },
  {
    name: "addresses.0.police_station",
    label: "Police Station",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_perm_police",
  },
  {
    name: "addresses.0.district",
    label: "District",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_perm_district",
  },
  {
    name: "addresses.0.state",
    label: "State",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_perm_state",
  },
  {
    name: "addresses.0.pincode",
    label: "Pincode",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_perm_pincode",
  },

  // ===== ADDRESS (CORRESPONDENCE) =====
  {
    section: "Correspondence Address",
    name: "addresses.1.village_mohalla",
    label: "Village / Mohalla",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_corr_village",
  },
  {
    name: "addresses.1.post_office",
    label: "Post Office",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_corr_post",
  },
  {
    name: "addresses.1.police_station",
    label: "Police Station",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_corr_police",
  },
  {
    name: "addresses.1.district",
    label: "District",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_corr_district",
  },
  {
    name: "addresses.1.state",
    label: "State",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_corr_state",
  },
  {
    name: "addresses.1.pincode",
    label: "Pincode",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_corr_pincode",
  },

  // ===== LAST ACADEMIC =====
  {
    section: "Last Academic Details",
    name: "last_academic.institute_name",
    label: "Institute Name",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_last_inst",
  },
  {
    name: "last_academic.class",
    label: "Class",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_last_class",
  },
  {
    name: "last_academic.session",
    label: "Session",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_last_session",
  },
  {
    name: "last_academic.section",
    label: "Section",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_last_section",
  },
  {
    name: "last_academic.roll_number",
    label: "Roll Number",
    type: FORM_TYPE.TEXT,
    required: true,
    permission: "field_admission_last_roll",
  },
];
