
import { type BreadcrumbItem } from '@/types';
import { Transition } from '@headlessui/react';
import { Head, useForm as useInertiaForm } from '@inertiajs/react';
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import HeadingSmall from '@/components/heading-small';
import { useRegisterGuide } from '@/components/GuideProvider';
import { PASSWORD_GUIDE } from '@/constants/guides/settings';
import { CHANGE_PASSWORD_FORM_CONFIG } from '@/constants/auth/changePasswordFormConfig';
import { changePasswordSchema, type ChangePasswordFormValues } from '@/lib/validations/changePassword';
import { AlertTriangle, KeyRound } from 'lucide-react';
import ControlledFormComponent from '@/components/shared/ControlledFormComponent';
import SettingsFooter from '@/components/shared/SettingsFooter';
import SettingsSection from '@/components/shared/SettingsSection';
import Each from '@/components/Each';
import { toast } from 'sonner';

export default function Password({ mustResetPassword }: { mustResetPassword?: boolean }) {
    const { control, handleSubmit, reset, formState: { isDirty } } = useForm<ChangePasswordFormValues>({
        resolver: zodResolver(changePasswordSchema),
        mode: "onChange",
    });

    useRegisterGuide(PASSWORD_GUIDE);

    const inertiaForm = useInertiaForm({
        current_password: '',
        password: '',
        password_confirmation: '',
    });

    const onSubmit = (data: ChangePasswordFormValues) => {
        inertiaForm.setData(data);
        inertiaForm.put(route('password.update'), {
            preserveScroll: true,
            onSuccess: () => {
                toast.success('Password updated successfully');
                reset();
            },
            onError: () => {
                toast.error('Failed to update password');
            },
        });
    };

    return (
        <>
            <Head title="Password settings" />

            <div className="space-y-6">
                    {mustResetPassword && (
                        <div className="flex items-start gap-4 rounded-xl border border-amber-200 bg-amber-50/50 p-4 backdrop-blur-sm shadow-sm">
                            <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-600" />
                            <div>
                                <p className="font-bold text-amber-900 leading-none">
                                    Password reset required
                                </p>
                                <p className="mt-2 text-sm text-amber-700 font-medium">
                                    Your password was auto-generated by the system. Please set a new password to continue using your account.
                                </p>
                            </div>
                        </div>
                    )}

                    <HeadingSmall
                        id="password-header"
                        guidance={PASSWORD_GUIDE}
                    />

                    <form
                        onSubmit={handleSubmit(onSubmit)}
                        className="mt-6 space-y-6 pb-10"
                    >
                        <SettingsSection
                            icon={KeyRound}
                            title="Update Password"
                            description="Ensure your account is using a long, random password to stay secure."
                        >
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-6">
                                <Each
                                    of={CHANGE_PASSWORD_FORM_CONFIG}
                                    render={(field) => (
                                        <ControlledFormComponent
                                            key={field.name}
                                            control={control}
                                            {...field}
                                        />
                                    )}
                                />
                            </div>
                        </SettingsSection>

                        <SettingsFooter
                            isDirty={isDirty}
                            isPending={inertiaForm.processing}
                            isSuccess={inertiaForm.recentlySuccessful}
                            onDiscard={() => reset()}
                            submitLabel="Commit Password"
                            successMessage="Password updated"
                        />
                    </form>
            </div>
        </>
    );
}


